project:
  type: website

website:
  title: "Moving Science Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Paeddasan
      - icon: twitter
        href: https://x.com/peterraidl
license: "CC BY 4.0"
format:
  html:
    theme: cosmo
    css: styles.css
bibliography: blog_Paeddasan.bib
editor: visual

