project:
  type: website

website:
  title: "embodymate"
  site-url: "https://paeddasan.github.io/blog/"
  description: "Blog on the Science of Human Movement by Peter Raidl"
  navbar:
    left:
      - text: "Home"
        href: "https://paeddasan.github.io/"
    right:
      - text: "The Moving Science Blog"
        href: "/"
      - icon: github
        href: https://github.com/Paeddasan/blog
      - icon: rss
        href: index.xml

license: "CC BY 4.0"

format:
  html:
    theme: cosmo
    css: styles.css

bibliography: Blog_Paeddasan.bib
bibliographystyle: apa.csl
editor: visual