---
title: "An Experiment on Attention"
author: "Peter Raidl"
date: "2025-05-31"
draft: True
---

Today I want to share a form of [movement practice](<https://themovingscienceblog.netlify.app/posts/nonfunctionaltraining/nonfunctionaltraining>) I engage in regularly.
I want to emphazise that this is not completely separate from a [training](https://themovingscienceblog.netlify.app/posts/a%20discussion%20on%20training/whatstraining) perspective, but primarily I am trying to see it as a practice. As you might already have realized, this is a very personal article. It hopefully serves as an example to the more theoretical, philosophical articles I posted so far.

The practice I do is based on the idea of willingly switching between internal and external focus during repeated exercises or movements. It is actually quite simple - which does not make it easy.

## Short introduction on focus and movement

When we have an external focus during movement, we direct our cognitive processes on the information we get and the effects we have on the external world. It is about the soccer goal, or the cup of tee we want to reach for. With an internal focus, on the other hand, we focus on our breathing, heartbeat or the way we use our muscles and joints when reaching for that cup. 

In research on motor control and learning internal and external focus have been of interest for decades now.
Most research points to a superiority of an external focus when it comes to learning and performance (<SOURCE>). On the other hand, there is something to say about an internal focus too. Many body-mind practices like Yoga, traditional martial arts and some contemporary dance arts use this form of attention[^1]. Also the modern mindfulness movement has a strong emphasis on internal processes. The conscious attention on internal processes is thought to improve our "understanding" of bodily sensations. This in turn improves our own understanding of emotions and feelings, because, as some prominent theories point out, emotions are interpretations of the feedback we get from our body coupled with situational cues.

[^1]: I use attention and focus interchangeably. But there might be a difference. Attention could be described as the process of directing your mental processes towards something, while focus is more about sustaining the attention on something.

## As practice
But it is not so much the scientific, exoteric promises of that practice. In contrast I want to arouse your curiosity about what happens during such a practice in YOU! To use a word some might find provocative - it is an esoteric practice - or to use the meaning of the word more specifically - it is about what you can find out about your own, individual reality, not what is generally known for a population [^2].
So when I now describe the practice make sure to understand that the explicit knowledge about *what it should be* is not of interest. It is about your *participatory knowing* and *what it is to you*. So I want to invite you to try it out - playful but seriously. Try it out a couple of times to really understand it  

[^2]: the word esoteric has many different meanings. Originally it was used as a differentiation from exoteric philosophies and it means something like "secret" or "inner" philosophy. Coming from a time when philosophy and science were two sides of the same coin, esoteric can mean something like the knowledge (or wisdom) that reveals itself only to the experts or the knowledge (or wisdom) that is only attainable through insight into onse own nature of reality.


