---
title: "Ignorantia"
author:
    - "Peter Raidl"
date: "2026-08-04"
categories: [blog, knowledge, learning, education]
draft: False

---

Knowledge is power, and data is the most precious currency of our times. We are trying to gather more information, and it has never been as easy to fact-check someone immediately. Knowledge is now more democratized and, to an extent, independent of education. Everything we need to know is at the tip of our thumbs. This raises a question that concerns everyone: 
**What do we need to know?**

This question should be chewed on properly. It's not just opening up a cynical or nihilistic perspective on learning. It rather questions our relationship to knowing and the unknown. 
When we think of our deepest discussions or our sparkling curiosity, we find that they are seldom driven by something we know and agree on. It's the wonders and mysteries that let us look up at the stars, have long conversations, or sudden creative insights. Firestein describes ignorance as the ingredient that drives science. The same can be said about every child that asks *Why* for the hundredth time [@firesteinIgnoranceHowIt2012]. 

I believe that if we stay on the route we are on and ask the *data-ferry* in our pockets for the factual answer the moment we are ignorant, we rob ourselves of the most fascinating moments and deepest insights. That is more than just the argument that we unlearn problem-solving or outsource our memory. Allegedly, the ancient Egyptians figured that writing would diminish their ability to memorize. But there are two sides to that story. Freeing the mind of one task opens the door to other tasks. Writing may have affected our working memory negatively, but it also became a powerful "psychotechnology" (Vervaeke), accelerating progress and insights in other domains. Something similar might happen with our accomplishments with silicon brains. But I argue that killing our ignorance is different, because it is not the development of skills alone that dies. What is endangered is the experience of the search itself.


Zen Koans are the ultimate ignorance test. *What is the sound of one hand clapping? Does the dog have Buddha nature? Who am I?* Students of Zen Buddhism sometimes sit with these kinds of "riddles" for many days or even months without knowing the answer. They are regularly interviewed by their teacher, but seldom is there a single correct answer to give. It is about the quest itself and everything that comes with it. It's about looking at the question from every direction; turning it around in one's mind; spitting it out and chewing it again. It's about the surprise when an insight comes out of nowhere during moments when we stop clinging - in the shower or during a walk. It's also about the frustration when the answer does not suffice and how one copes with that.

Ignorance and the unknown are the invitation to a Koan and the spice of life. Not engaging in the ignorance is not the nihilistic answer to what we need to know. It is the denial of the Koan.
Whether the liberation of fast information is a farce or a genuine blessing is still to be discovered. But for now, we should reframe the question *what we need to know*. 
  
<!--#  NOTES
Ignorance is even more. It allows many aspects of our lives. We can only be creative when we find the edge of our resources - including information. 
Ignorance helps us overcome our biases. When grading students' assignments, I anonymize their work beforehand. 
When creating statistical models, we need unknown data points for evaluation of generalizability and robustness. 
Ignorance is necessary when making decisions. Millions of collective hours have been wasted ruminating on the unknown paths instead of making a decision. Many exercise programs and diets never started or faded quickly because of the search for something better - and so did many relationships. 
We want to stay ignorant to the end of a movie before seeing it, and we enjoy unpacking a present maybe more than the gift itself. 
--> 


